App As appinfo:
    BackEnabled: =false
    ConfirmExit: =false
    ConfirmExitMessage: =""
    DefaultConnectedDataSourceMaxGetRowsCount: =500
    EnableAppEmbedding: =false
    EnableDelayActions: =false
    EnableDelayOutput: =true
    EnableHeaderBarHiding: =false
    EnablePowerAutomate: =true
    LoadingSpinner: =LoadingSpinner.Controls
    LoadingSpinnerColor: =RGBA(135, 100, 184, 1)
    Name: ="ECR Data Collector"
    ShowViewInMR: =true

